#!/bin/bash
#assignment: write a script that reads from a file and outputs to another

file="./states.txt"

while read -r line; do
  if [[ ! $line =~ ^[A-Z] ]]
  then
    echo "Orthographic error: $line isn't capitalized"
  elif [[ $line =~ [^a-zA-Z][a-z] ]]
  then
    echo "Orthographic error: $line contains a word that isn't capitalized"
  elif [[ $line =~ [a-zA-Z][A-Z] ]]
  then
    echo "Orthographic error: $line contains an improperly capitalized character"
  else
    echo $line >> formatted.txt
  fi
done < $file
